description: >
  Install AWS CLI, if needed, and configure. Log into Amazon ECR and push image
  to repository. Requires environment variables for AWS_ACCESS_KEY_ID and
  AWS_SECRET_ACCESS_KEY. We recommend these be saved in a Project
  (https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-project)
  or in Contexts (https://circleci.com/docs/2.0/contexts).
parameters:
  account-url:
    default: AWS_ECR_ACCOUNT_URL
    description: >
      Env var storing Amazon ECR account URL that maps to an AWS account, e.g.
      {awsAccountNum}.dkr.ecr.us-west-2.amazonaws.com defaults to
      AWS_ECR_ACCOUNT_URL
    type: env_var_name
  attach-workspace:
    default: false
    description: >
      Boolean for whether or not to attach to an existing workspace. Default is
      false.
    type: boolean
  aws-access-key-id:
    default: AWS_ACCESS_KEY_ID
    description: >
      AWS access key id for IAM role. Set this to the name of the environment
      variable you will set to hold this value, i.e. AWS_ACCESS_KEY.
    type: env_var_name
  aws-secret-access-key:
    default: AWS_SECRET_ACCESS_KEY
    description: >
      AWS secret key for IAM role. Set this to the name of the environment
      variable you will set to hold this value, i.e. AWS_SECRET_ACCESS_KEY.
    type: env_var_name
  checkout:
    default: true
    description: |
      Boolean for whether or not to checkout as a first step. Default is true.
    type: boolean
  create-repo:
    default: false
    description: Should the repo be created if it does not exist?
    type: boolean
  dockerfile:
    default: Dockerfile
    description: Name of dockerfile to use. Defaults to Dockerfile.
    type: string
  executor:
    default: default
    description: executor to use for this job
    type: executor
  extra-build-args:
    default: ''
    description: >
      Extra flags to pass to docker build. For examples, see
      https://docs.docker.com/engine/reference/commandline/build
    type: string
  no-output-timeout:
    default: 10m
    description: >
      The amount of time to allow the docker build command to run before timing
      out (default is `10m`)
    type: string
  path:
    default: .
    description: >-
      Path to the directory containing your Dockerfile and build context.
      Defaults to . (working directory).
    type: string
  profile-name:
    default: default
    description: AWS profile name to be configured.
    type: string
  region:
    default: AWS_REGION
    description: >
      Name of env var storing your AWS region information, defaults to
      AWS_REGION
    type: env_var_name
  repo:
    description: Name of an Amazon ECR repository
    type: string
  setup-remote-docker:
    default: false
    description: >
      Setup and use CircleCI's remote Docker environment for Docker and
      docker-compose commands? Not required if using the default executor
    type: boolean
  tag:
    default: latest
    description: >-
      A comma-separated string containing docker image tags to build and push
      (default = latest)
    type: string
  workspace-root:
    default: .
    description: >
      Workspace root path that is either an absolute path or a path relative to
      the working directory. Defaults to '.' (the working directory)
    type: string
steps:
  - when:
      condition: <<parameters.checkout>>
      steps:
        - checkout
  - aws-cli/install
  - aws-cli/configure:
      aws-access-key-id: <<parameters.aws-access-key-id>>
      aws-region: <<parameters.region>>
      aws-secret-access-key: <<parameters.aws-secret-access-key>>
      profile-name: <<parameters.profile-name>>
  - when:
      condition: <<parameters.attach-workspace>>
      steps:
        - attach_workspace:
            at: <<parameters.workspace-root>>
  - when:
      condition: <<parameters.setup-remote-docker>>
      steps:
        - setup_remote_docker
  - ecr-login:
      region: <<parameters.region>>
  - build-image:
      account-url: <<parameters.account-url>>
      dockerfile: <<parameters.dockerfile>>
      extra-build-args: <<parameters.extra-build-args>>
      no-output-timeout: <<parameters.no-output-timeout>>
      path: <<parameters.path>>
      repo: <<parameters.repo>>
      tag: <<parameters.tag>>
  - when:
      condition: <<parameters.create-repo>>
      steps:
        - run: >
            aws ecr describe-repositories --profile <<parameters.profile-name>>
            --region $<<parameters.region>> --repository-names
            <<parameters.repo>> > /dev/null 2>&1 || \

            aws ecr create-repository --profile <<parameters.profile-name>>
            --region $<<parameters.region>> --repository-name
            <<parameters.repo>>
  - push-image:
      account-url: <<parameters.account-url>>
      repo: <<parameters.repo>>
      tag: <<parameters.tag>>
